# @timeout 600
POST http://localhost:8000/fhir/ViewDefinition/$run
Content-Type: application/fhir+json
Accept: text/csv

{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "viewDefinition",
      "resource": {
        "resourceType": "https://sql-on-fhir.org/ig/StructureDefinition/ViewDefinition",
        "select": [
          {
            "column": [
              {"path": "getResourceKey()", "name": "id"},
              {"path": "gender", "name": "gender"}
            ]
          },
          {
            "forEach": "name.where(use = 'official').first()",
            "column": [
              {"path": "given.join(' ')", "name": "given_name", "description": "A single given name field with all names joined together."},
              {"path": "family", "name": "family_name"}
            ]
          }
        ],
        "name": "patient_demographics",
        "status": "draft",
        "resource": "Patient"
      }
    },
    {
      "name": "resources",
      "resource": {
        "resourceType": "Patient",
        "id": "1",
        "gender": "male",
        "birthDate": "1959",
        "deceasedBoolean": false,
        "name": [
          {
            "use": "official",
            "given": ["John"],
            "family": "Jackson"
          }
        ]
      }
    },
    {
      "name": "resources",
      "resource": {
        "resourceType": "Patient",
        "id": "2",
        "gender": "male",
        "birthDate": "1959",
        "deceasedBoolean": true,
        "name": [
          {
            "use": "official",
            "given": ["Jack"],
            "family": "Johnson"
          }
        ]
      }
    }
  ]
}

###
# @timeout 600
POST http://localhost:8000/fhir/ViewDefinition/$run
Content-Type: application/fhir+json
Accept: text/csv

< src/test/resources/nested-sample.json
